### ISSUE TITLE
Change language of default share labels buttons

### ISSUE THREAD

**Issue by cmeiller** [react-native-community/react-native-share#720]
Hi, I would like to change the language of default share labels buttons (like Copy, Cancel, Add to Reading List...) to French trads. The device is in french but the share labels are still in english. Any solutions?

**Comment by MateusAndrade** [comment]
Hey @cmeiller , this is a good question. Do you mean "native" labels when calling the `Share` method? As far i remember, there ins't a way to customize that. But, prs are always welcome! 😄

**Comment by cmeiller** [comment]
@MateusAndrade yes these labels:
![labels-share](https://user-images.githubusercontent.com/412839/77155898-8c555100-6a9e-11ea-9090-b5dee6e28eef.jpg)

**Comment by sercanuste** [comment]
I found solution. 

Changing CFBundleDevelopmentRegion at Info.plist changes default language of share buttons. And adding CFBundleAllowMixedLocalizations allows multi-language support for Native Component.

```XML
<key>CFBundleDevelopmentRegion</key>
<string>fr</string>
<key>CFBundleAllowMixedLocalizations</key>
<string>true</string>
```

**Comment by cmeiller** [comment]
@sercanuste Amazing! I didn't think about it, thanks!

**Comment by MateusAndrade** [comment]
I merged #749 warning about this on our Docs. Thanks, @sercanuste 🎉 🎉 🎉 !

Do you think we can close this @cmeiller?

**Comment by cmeiller** [comment]
@MateusAndrade Absolutely! 😊

**Comment by lokomass** [comment]
@cmeiller can you explain how you I have done ?
I’ve trying @sercanuste solution but this doesnt work

**Comment by tlow92** [comment]
> I found solution.
> 
> Changing CFBundleDevelopmentRegion at Info.plist changes default language of share buttons. And adding CFBundleAllowMixedLocalizations allows multi-language support for Native Component.
> 
> ```
> <key>CFBundleDevelopmentRegion</key>
> <string>fr</string>
> <key>CFBundleAllowMixedLocalizations</key>
> <string>true</string>
> ```

I've tried this, with setting region to de (for german) and allowing mixed localizations but still getting half german half english share bottomsheet. 

`	<key>CFBundleDevelopmentRegion</key>
	<string>de</string>
	<key>CFBundleAllowMixedLocalizations</key>
  <string>true</string>`

![image](https://user-images.githubusercontent.com/12113052/123587047-f900e480-d7e5-11eb-8c36-38ddaa7ece45.png)

**Comment by artur-burlak** [comment]
@tlow92 did you find the solution? I also have mixed DE and EN
